### PR TITLE
Test Todo 

### PR DESCRIPTION
**Pull request by rahalrazika**
A test for the To-do list project using jest :
- Setup the jest test environment 
-  Write the test and make all the test to  pass

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @rahalrazika and @lirad  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the minimum requirements of this project, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] Make sure that you test all of the methods you have in your project, currently you have tested few of them, you will need to test all of the methods you have in all files.

# [Optional changes] :yellow_circle: 
- [x] Since you have `yarn.lock` file, then there is no point of keeping `package-lock.json` file in your repository. They both perform the same action, so it would be very nice if you remove one of them. `yarn.lock` => is for yarn users, `package-lock.json` => is for npm users. So, a good idea is to choose one to go with, and stick on it.
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑

### Hello team 👋,

**Great job implementing the requested changes 👏.**

### Highlights

- **Linters are properly configured.**
- **README file looks professional.**

### Mandatory Requirements

1). **Add tests for the following functionalities.**

- **When a user creates a new project.**
- **When a user adds a new todo list (You wrote one but it doesn't test addItem() function.).**
- **When a user checks a todo list as completed.**
- **When a user deletes a todo list.**

### Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

**Review by christianotieno — APPROVED** [review]
### Milestone Approved 🍾 
Hello @rahalrazika & @lirad 👋 
 ##
This testing-todo project has met all the requirements needed for approval. 👏 
Congratulations on the hard work done on this project. Good job 👍 
I will go ahead and mark this as complete. Good luck with the next tasks 🥇 
##
### Happy coding 💻 
#### Christian Otieno (CR)

**Pull request merged**
